name: o3d
description: The Flutter 3D objects easy controller ( glb format ) on mobile and web platforms
version: 3.1.2-dev-1
homepage: https://github.com/babakcode/o3d
topics:
  - "model"
  - "models3d"
  - "flutter3d"
  - "glb"
  - "model3d"

screenshots:
  - description: 'Examples of the o3d package.'
    path: example/screenshots/s1.png
  - description: 'Examples of the o3d package.'
    path: example/screenshots/s2.png

platforms:
  android:
  ios:
  web:

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  android_intent_plus: ^5.0.2
  flutter:
    sdk: flutter
  path: ^1.9.0
  url_launcher: ^6.2.6
  web: ^0.5.1
  webview_flutter: ^4.8.0
  webview_flutter_android: ^3.16.0
  webview_flutter_wkwebview: ^3.13.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
   - assets/